language: generic

services:
  - docker

matrix:
  include:
    - env: TARGET=build IMAGE=cern/slc5-base VERSION=4.2.0
    - env: TARGET=devel IMAGE=cern/slc5-base
    - env: TARGET=build IMAGE=cern/slc6-base VERSION=4.2.0
    - env: TARGET=devel IMAGE=cern/slc6-base

install:
  - ./scripts/travis.sh install

script:
  - ./scripts/travis.sh env
  - ./scripts/travis.sh script
