language: generic

services:
  - docker

matrix:
  include:
    - env: TARGET=build IMAGE=opensuse/leap:42.3 VERSION=4.2.0
    - env: TARGET=devel IMAGE=opensuse/leap:42.3
    - env: TARGET=build IMAGE=opensuse/leap:15.0 VERSION=4.2.0
    - env: TARGET=devel IMAGE=opensuse/leap:15.0

install:
  - ./scripts/travis.sh install

script:
  - ./scripts/travis.sh script
